<?php
/**
* @File Grouping module for the BuzzMonitor suite.
*/


/** 
*
**/
function buzzmonitor_mention_node_type() {
  return 'mention';
}


/**
* Create new term in a specified vocabulary or 
* return the name of an existing term. This is
* a safe function, not necessarily a very fast one (3 queries in the worst case).
*/
function _buzz_term_save( $name, $vocab_id=-1) {

  if ($vocab_id==-1) { return -1;}
  
  $existing_tid = db_result(db_query("SELECT tid FROM {term_data} WHERE vid=%d AND name='%s'", $vocab_id, $name));
  
  if (!empty($existing_tid) && $existing_tid > 0) {
    return $existing_tid;
  }

  $form = array(
    'vid' => $vocab_id,
    'name' => $name,
  );
  
  $status = taxonomy_save_term($form);
  
  $new_tid = db_result(db_query("SELECT tid FROM {term_data} WHERE vid=%d AND name='%s'", $vocab_id, $name));
  return $new_tid;

}