<?php

define('SOURCE_CONTENT_TYPE', 'source');
define('SOURCE_URL_FIELD', 'field_url');
define('MENTION_SOURCE_FIELD', 'field_source');
define('MENTION_COUNT_FIELD', 'field_mention_count');
define('TECHNORATI_AUTHORITY_FIELD', 'field_technorati_authority');
define('ALEXA_RANK_FIELD', 'field_alexa_rank');
define('ALEXA_LAST_UPDATE_FIELD', 'field_alexa_last_update');
define('TECHNORATI_LAST_UPDATE_FIELD', 'field_technorati_last_update');
define('COMBINED_RANK_FIELD', 'field_combined_rank');
define('MAX_ALEXA_RANK', 1000000);
define('MAX_COMPETE_RANK', 1000000);
define('MAX_TECHNORATI_AUTHORITY', 40000);